django_insights/urls.py
from django.urls import path

from django_insights import views

app_name = "insights"

urlpatterns = [
    path(
        'app/<uuid:app_uuid>/',
        views.InsightsAppView.as_view(),
        name="insight_app",
    ),
    path(
        'pdf/test/',
        views.InsightsPDFTestView.as_view(),
        name="insight_pdf_test",
    ),
    path(
        'pdf/',
        views.InsightsPDFView.as_view(),
        name="insight_pdf",
    ),
    path(
        'charts/<int:bucket_id>/',
        views.InsightsChartView.as_view(),
        name="insight_chart",
    ),
    path(
        '',
        views.InsightsDashboardView.as_view(),
        name="insight_dashboard",
    ),
]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include, path

urlpatterns = (
    [
        path(
            '',
            include('django_insights.urls', namespace='insights'),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

django_insights/models.py
import uuid

from django.db import models
from django.utils import timezone

from django_insights.choices import BucketType
from django_insights.database import database_entry
from django_insights.managers import BucketManager


class App(models.Model):
    """
    Apps that have insights

    """

    uuid = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True)
    module = models.CharField(max_length=254, db_index=True, unique=True)
    label = models.CharField(max_length=254, null=True)

    @property
    def name(self) -> str:
        return self.label or self.module


class ExecutionDelta(models.Model):
    """
    Delta is stored on every run and used for filtering, these values should never change

    """

    executed_at = models.DateTimeField(db_index=True, default=timezone.now)
    uuid = models.UUIDField(default=uuid.uuid4)


class MetricModel(models.Model):
    created_at = models.DateTimeField(db_index=True, default=timezone.now)
    label = models.CharField(max_length=254, db_index=True, unique=True)

    question = models.TextField(blank=True, null=True)
    desc = models.TextField(blank=True, null=True)

    class Meta:
        abstract = True


class Counter(MetricModel):
    """
    Simple counter, can incr or decr, label and app are unique

    """

    value = models.IntegerField(default=0)
    app = models.ForeignKey(App, related_name='counters', on_delete=models.CASCADE)

    class Meta:
        app_label = database_entry
        constraints = [
            models.UniqueConstraint(
                fields=['app', 'label'], name='counter_unique_app_label'
            )
        ]

    def __str__(self):
        return f"Insight Counter: {self.label} = {self.value}"


class Gauge(MetricModel):
    """
    Simple gauge, can be set or set with delta, label and app are unique

    """

    value = models.FloatField(default=float(0.0))
    app = models.ForeignKey(App, related_name='gauges', on_delete=models.CASCADE)

    def gauge(self, value=1, delta=False) -> int:
        """Set gauge value"""
        if not delta:
            self.value = value
        else:
            self.value = self.value + value

    class Meta:
        app_label = database_entry
        constraints = [
            models.UniqueConstraint(
                fields=['app', 'label'], name='gauge_unique_app_label'
            )
        ]

    def __str__(self):
        return f"Insight Gauge: {self.label} = {self.value}"


class Bucket(MetricModel):
    app = models.ForeignKey(App, related_name='buckets', on_delete=models.CASCADE)

    type = models.IntegerField(
        choices=BucketType.BUCKET_TYPES, default=BucketType.TIMESERIES
    )

    # Bucket specific plot options
    xlabel = models.CharField(max_length=254, blank=True, null=True)
    xformat = models.CharField(max_length=254, blank=True, null=True)
    ylabel = models.CharField(max_length=254, blank=True, null=True)
    yformat = models.CharField(max_length=254, blank=True, null=True)

    # title for plot
    title = models.CharField(max_length=254, blank=True, null=True)

    @property
    def is_timeseries(self) -> bool:
        return self.type == BucketType.TIMESERIES

    @property
    def is_histogram(self) -> bool:
        return self.type == BucketType.HISTOGRAM

    @property
    def is_scatterplot(self) -> bool:
        return self.type == BucketType.SCATTERPLOT

    @property
    def is_barchart(self) -> bool:
        return self.type == BucketType.BARCHART

    @property
    def is_hbarchart(self) -> bool:
        return self.type == BucketType.HBARCHART

    objects = BucketManager()

    class Meta:
        app_label = database_entry
        constraints = [
            models.UniqueConstraint(
                fields=[
                    'app',
                    'label',
                ],
                name='bucket_unique_app_label_timestamp',
            )
        ]


class BucketValue(models.Model):
    """
    Bucket values matrix: used for time-series, histogram and scatterpltos.
    Combination of timestamp, label and app are unique.

    """

    # Timestamp for timeseries
    timestamp = models.DateTimeField(db_index=True, blank=True, null=True)

    # Matrix
    xvalue = models.FloatField(default=float(0.0))
    yvalue = models.FloatField(default=float(0.0))
    category = models.CharField(db_index=True, max_length=254, null=True)

    bucket = models.ForeignKey(Bucket, related_name='values', on_delete=models.CASCADE)

    class Meta:
        app_label = database_entry
        constraints = [
            models.UniqueConstraint(
                fields=['bucket', 'timestamp'],
                name='bucketvalue_unique_bucket_timestamp',
            )
        ]

    def __str__(self):
        return (
            "Insight Bucket value: "
            f" timestamp={self.bucket.label}.{self.timestamp} x={self.xvalue} y={self.yvalue}"
        )

django_insights/views.py
from __future__ import annotations

import asyncio
import os
from typing import Any, Callable

from asgiref.sync import sync_to_async
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models.query import QuerySet
from django.http import HttpResponse
from django.utils.decorators import classonlymethod
from django.views.generic import DetailView, ListView, View
from django_weasyprint import WeasyTemplateResponseMixin

from django_insights.charts import (
    barchart,
    hbarchart,
    scatterplot,
    timeseries,
    to_bytes_io,
)
from django_insights.models import App, Bucket, Counter, Gauge
from django_insights.settings import settings


class CustomPermissionMixin(UserPassesTestMixin):

    """
    Run following permisssion

    class IsSomeAdminUser:
        def has_permission(self, request):
            return
    """

    def run_permissions(self, permissions: list[Callable]) -> list[bool]:
        """
        Run all permission checks from INSIGHT_DASHBOARD_PERMISSIONS settings
        and return output in array
        """
        return [
            permission().has_permission(request=self.request)
            for permission in permissions
            if hasattr(permission(), 'has_permission')
        ]

    def test_func(self):
        return (
            all(self.run_permissions(settings.INSIGHT_DASHBOARD_PERMISSIONS))
            if settings.INSIGHT_DASHBOARD_PERMISSIONS
            else True
        )


class InsightAppMixin(
    LoginRequiredMixin,
    CustomPermissionMixin,
    View,
):
    apps: list[App] = []

    def get_apps(self) -> QuerySet[App]:
        if not self.apps:
            self.apps = App.objects.all()
        return self.apps

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update(
            {'app_name': settings.INSIGHTS_APP_NAME, 'apps': self.get_apps()}
        )
        return context


class InsightsAppView(InsightAppMixin, DetailView):
    model = App
    slug_field = 'uuid'
    slug_url_kwarg = 'app_uuid'
    template_name = "insights/app.html"

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        app = self.get_object()

        context = super().get_context_data(**kwargs)
        context.update({'app_label': app.name})
        return context


class InsightsDashboardView(InsightAppMixin, ListView):
    template_name = "insights/dashboard.html"

    def get_queryset(self) -> list[Any]:
        # Get all metrics in one query?
        return Counter.objects.all()

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context.update({'gauges': Gauge.objects.all(), 'app_label': 'Dashboard'})
        return context


@sync_to_async
def get_bucket(bucket_id: int) -> Bucket:
    """Get bucket from async context"""
    return Bucket.objects.get(pk=bucket_id)


class InsightsChartView(LoginRequiredMixin, View):
    @classonlymethod
    def as_view(cls, **initkwargs):
        view = super().as_view(**initkwargs)
        view._is_coroutine = asyncio.coroutines._is_coroutine
        return view

    async def get(self, request, bucket_id):
        theme = self.request.COOKIES.get('theme') or settings.INSIGHTS_DEFAULT_THEME
        bucket: Bucket = await get_bucket(bucket_id)

        filename: str = (
            f"{settings.INSIGHT_MEDIA_CACHE_ROOT}/{bucket.type}-{bucket.pk}-{theme}.png"
        )

        if os.path.exists(filename) and settings.INSIGHT_CHARTS_USE_MEDIA_CACHE:
            with open(filename, 'rb') as cached_image:
                buffer = cached_image.read()

            return HttpResponse(buffer, content_type='image/png')

        fig = None

        if bucket.is_timeseries:
            fig = await timeseries(bucket, theme=theme)
        if bucket.is_scatterplot:
            fig = await scatterplot(bucket, theme=theme)
        if bucket.is_barchart:
            fig = await barchart(bucket, theme=theme)
        if bucket.is_hbarchart:
            fig = await hbarchart(bucket, theme=theme)

        buffer = to_bytes_io(fig)

        if settings.INSIGHT_CHARTS_USE_MEDIA_CACHE:
            with open(filename, 'wb') as cached_image:
                cached_image.write(buffer)

        return HttpResponse(buffer, content_type='image/png')


class InsightsPDFView(WeasyTemplateResponseMixin, InsightAppMixin, ListView):
    """Render PDF"""

    queryset = App.objects.all()

    pdf_stylesheets = [
        settings.STATIC_ROOT + 'insights/css/pdf.css',
    ]

    template_name = 'insights/pdf.html'
    pdf_attachment = False
    pdf_filename = 'foo.pdf'


class InsightsPDFTestView(InsightAppMixin, ListView):
    """Render PDF HTML as test"""

    queryset = App.objects.all()

    pdf_stylesheets = [
        settings.STATIC_ROOT + 'insights/css/pdf.css',
    ]

    def get_template_names(self):
        return ['insights/pdf.html']

    def get_context_data(self, **kwargs: Any) -> dict[str, Any]:
        data = super().get_context_data(**kwargs)

        data.update(
            {
                'test_mode': True,
                'test_stylesheet': 'insights/css/pdf.css',
            }
        )

        return data

django_insights/templates/insights/base.html
{% load static %}
{% url 'insights:insight_dashboard' as dashboard_url %}
<!doctype html>
<html id="html-root" lang="en">
    <title>{{ app_name }} - Insights</title>
    <head>
        <meta charset="UTF-8" />
        <meta lang="en" />
        <meta keywords="{{ app_name }}, insights" />
        <meta description="{{ app_name }} - Insights" />
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=ubuntu:300,300i,400,400i,500,500i,700,700i" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'insights/css/insights.css' %}" />
        <script src="{% static 'insights/js/insights.js' %}" defer></script>
    </head>
    <body class="bg-background text-foreground dark:bg-foreground dark:text-background">
        <div class="sticky inset-x-0 top-0 z-20 px-4 bg-white border-b drop-shadow-sm sm:px-6 md:px-8 dark:border-b-gray-900 dark:bg-foreground">
            <div class="flex items-center py-1">
                <!-- Navigation Toggle -->
                <button type="button"
                        class="text-gray-500 hover:text-gray-600"
                        data-hs-overlay="#application-sidebar"
                        aria-controls="application-sidebar"
                        aria-label="Toggle navigation">
                    <span class="sr-only">Toggle Navigation</span>
                    <svg class="w-5 h-5"
                         width="16"
                         height="16"
                         fill="currentColor"
                         viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
                    </svg>
                </button>
                <!-- End Navigation Toggle -->
                <!-- Breadcrumb -->
                <ol class="flex items-center flex-grow min-w-0 ml-3 whitespace-nowrap"
                    aria-label="Breadcrumb">
                    <li class="flex items-center text-sm text-gray-800 dark:text-gray-400">
                        {{ app_name }}
                        <svg class="flex-shrink-0 mx-3 overflow-visible h-2.5 w-2.5 text-gray-400 dark:text-gray-600"
                             width="16"
                             height="16"
                             viewBox="0 0 16 16"
                             fill="none"
                             xmlns="http://www.w3.org/2000/svg">
                            <path d="M5 1L10.6869 7.16086C10.8637 7.35239 10.8637 7.64761 10.6869 7.83914L5 14" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
                        </svg>
                    </li>
                    <li class="text-sm font-semibold text-gray-800 truncate dark:text-gray-400"
                        aria-current="page">{{ app_label }}</li>
                </ol>
                <button id="mode-toggle"
                        class="p-2 rounded-sm hover:bg-gray-100 dark:hover:bg-gray-900">
                    <svg xmlns="http://www.w3.org/2000/svg"
                         fill="none"
                         viewBox="0 0 24 24"
                         stroke-width="1.5"
                         stroke="currentColor"
                         class="w-4 h-4">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M12 3v2.25m6.364.386l-1.591 1.591M21 12h-2.25m-.386 6.364l-1.591-1.591M12 18.75V21m-4.773-4.227l-1.591 1.591M5.25 12H3m4.227-4.773L5.636 5.636M15.75 12a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0z" />
                    </svg>
                </button>
                <!-- End Breadcrumb -->
            </div>
        </div>
        <div id="data-copied-msg" class="hidden bg-green-50 border border-green-200 text-sm text-green-600 p-4" role="alert">
            <span class="font-bold">Data copied</span> copy of the data is now on your clipboard.
        </div>
        <!-- Sidebar -->
        <div id="application-sidebar"
             class="hs-overlay hs-overlay-open:translate-x-0 -translate-x-full transition-all duration-300 transform hidden fixed top-0 left-0 bottom-0 z-[60] w-64 bg-white border-r border-gray-200 pt-7 pb-10 overflow-y-auto scrollbar-y dark:scrollbar-y dark:bg-foreground dark:border-foreground">
            <div class="px-6">
                <a class="flex-none" href="{{ dashboard_url }}">
                    <span class="text-xl font-semibold text-primary-500">{{ app_name }}</span>
                    <span class="inline-block align-top dark:text-white">Insights</span>
                </a>
            </div>
            <nav class="flex flex-col flex-wrap w-full p-6">
                <ul class="space-y-1.5">
                    <li>
                        <a class="flex items-center gap-x-3.5 py-2 px-2.5 bg-gray-100 text-sm text-slate-700 rounded-md hover:bg-gray-100 dark:bg-gray-900 dark:text-white"
                           href="{{ dashboard_url }}">
                            <svg class="w-3.5 h-3.5"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="16"
                                 height="16"
                                 fill="currentColor"
                                 viewBox="0 0 16 16">
                                <path fill-rule="evenodd" d="M2 13.5V7h1v6.5a.5.5 0 0 0 .5.5h9a.5.5 0 0 0 .5-.5V7h1v6.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5zm11-11V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                                <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
                            </svg>
                            Dashboard
                        </a>
                    </li>
                    {% for app in apps %}
                        {% url 'insights:insight_app' app_uuid=app.uuid as app_url %}
                        <li>
                            <a class="flex items-center gap-x-3.5 py-2 px-2.5 text-sm text-slate-700 rounded-md hover:bg-gray-100 dark:hover:bg-gray-900 dark:text-slate-400 dark:hover:text-slate-300"
                               href="{{ app_url }}">
                                {{ app.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </nav>
        </div>
        <div class="w-full px-4 pt-4 sm:px-6 md:px-8">
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

django_insights/templates/insights/dashboard.html
{% extends "insights/base.html" %}
{% block content %}
    <!-- Card Section -->
    <div class="max-w-[85rem]">
        <!-- Grid -->
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 sm:gap-6">
            {% for counter in counter_list %}
                <div class="flex flex-col border shadow-sm border-slate-200 dark:border-slate-900 bg-background text-foreground dark:bg-foreground dark:text-background rounded-xl">
                    <div class="p-4 md:p-5">
                        <div class="flex items-center gap-x-2">
                            <p class="text-xs tracking-wide text-gray-500 uppercase">{{ counter.question }}</p>
                            {% if counter.desc %}
                                <div class="hs-tooltip">
                                    <div class="hs-tooltip-toggle">
                                        <svg class="w-3.5 h-3.5 text-gray-500"
                                             xmlns="http://www.w3.org/2000/svg"
                                             width="16"
                                             height="16"
                                             fill="currentColor"
                                             viewBox="0 0 16 16">
                                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                            <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
                                        </svg>
                                        <span class="absolute z-10 invisible inline-block px-2 py-1 text-xs font-medium text-white transition-opacity bg-gray-900 rounded-md shadow-sm opacity-0 dark:text-gray-50 hs-tooltip-content hs-tooltip-shown:opacity-100 hs-tooltip-shown:visible dark:bg-slate-900"
                                              role="tooltip">
                                            {{ counter.desc }}
                                        </span>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <div class="flex items-center mt-1">
                            <h3 class="text-xl font-medium text-gray-800 sm:text-2xl dark:text-gray-200">{{ counter.value }}</h3>
                            <span class="flex items-center text-gray-500">
                                <span class="inline-block p-2 text-xs">x</span>
                            </span>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% for gauge in gauges %}
                <div class="flex flex-col border shadow-sm border-slate-50 bg-background text-foreground dark:bg-foreground dark:text-background rounded-xl">
                    <div class="p-4 md:p-5">
                        <div class="flex items-center gap-x-2">
                            <p class="text-xs tracking-wide text-gray-500 uppercase">{{ gauge.question }}</p>
                            <div class="hs-tooltip">
                                <div class="hs-tooltip-toggle">
                                    <svg class="w-3.5 h-3.5 text-gray-500"
                                         xmlns="http://www.w3.org/2000/svg"
                                         width="16"
                                         height="16"
                                         fill="currentColor"
                                         viewBox="0 0 16 16">
                                        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                        <path d="M5.255 5.786a.237.237 0 0 0 .241.247h.825c.138 0 .248-.113.266-.25.09-.656.54-1.134 1.342-1.134.686 0 1.314.343 1.314 1.168 0 .635-.374.927-.965 1.371-.673.489-1.206 1.06-1.168 1.987l.003.217a.25.25 0 0 0 .25.246h.811a.25.25 0 0 0 .25-.25v-.105c0-.718.273-.927 1.01-1.486.609-.463 1.244-.977 1.244-2.056 0-1.511-1.276-2.241-2.673-2.241-1.267 0-2.655.59-2.75 2.286zm1.557 5.763c0 .533.425.927 1.01.927.609 0 1.028-.394 1.028-.927 0-.552-.42-.94-1.029-.94-.584 0-1.009.388-1.009.94z"/>
                                    </svg>
                                    <span class="absolute z-10 invisible inline-block px-2 py-1 text-xs font-medium text-white transition-opacity bg-gray-900 rounded-md shadow-sm opacity-0 dark:text-gray-50 hs-tooltip-content hs-tooltip-shown:opacity-100 hs-tooltip-shown:visible dark:bg-slate-900"
                                          role="tooltip">
                                        {{ gauge.desc }}
                                    </span>
                                </div>
                            </div>
                        </div>
                        <div class="flex items-center mt-1">
                            <h3 class="text-xl font-medium text-gray-800 sm:text-2xl dark:text-gray-200">{{ gauge.value }}</h3>
                            <span class="flex items-center text-gray-500">
                                <span class="inline-block p-2 text-xs">%</span>
                            </span>
                            <div>
                                <div class="flex flex-col justify-center overflow-hidden bg-blue-500"
                                     role="progressbar"
                                     style="width: 25%"
                                     aria-valuenow="{{ gauge.value }}"
                                     aria-valuemin="0"
                                     aria-valuemax="100">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            <!-- End Card -->
        </div>
        <!-- End Grid -->
    </div>
    <!-- End Card Section -->
{% endblock content %}

django_insights/templates/insights/pdf.html
{% load static nice_format insight_chart %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Report {{ app_name }}</title>
    <meta name="description" content="Insights report">
    {% if test_mode %}
      <link href="{% static test_stylesheet %}" rel="stylesheet" />
    {% endif %}
  </head>
  <body>
    <article id="cover">
      <h1>Insights {{ app_name }}</h1>
    </article>
    {% for app in object_list %}
      <article id="columns">
        <h2>{{ app.name }}</h2>
        <div class="counters">
          {% for counter in app.counters.all %}
            {% if counter %}
              <!-- Counter -->
              <div>
                <p>{{ counter.question }}</p>
                <div class="stats">
                  <h3>{{ counter.value }}</h3>
                  <span class="stats">
                    <span class="counter">x</span>
                  </span>
                </div>
              </div>
              <!-- End Counter Section -->
            {% endif %}
          {% endfor %}
          {% for gauge in app.gauges.all %}
            {% if gauge %}
              <!-- Gauges -->
              <div>
                <p>{{ gauge.question }}</p>
                <div class="stats">
                  <h3>{{ gauge.value }}</h3>
                  <span class="stats">
                    <span class="counter">%</span>
                  </span>
                </div>
              </div>
              <!-- End Gauges Section -->
            {% endif %}
          {% endfor %}
        </div>
        <div class="pagebreak" />
        {% for bucket in app.buckets.timeseries %}
          {% if bucket %}
            <h3>{{ bucket.question }}</h3>
            <p>{{ bucket.desc }}</p>
            {% pdf_chart bucket.pk %}
            <section>
              <!-- Table -->
              <table>
                <thead>
                  <tr>
                    <th scope="col">{{ bucket.xlabel }}</th>
                    <th scope="col">{{ bucket.ylabel }}</th>
                  </tr>
                </thead>
                <tbody>
                  {% for bucket_value in bucket.values.all %}
                    <tr>
                      <td>{{ bucket_value.timestamp|date:bucket.xformat|clean_str:"%" }}</td>
                      <td>{{ bucket_value.xvalue|nice_float }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
              <!-- End Table Section -->
            </section>
            {% if not forloop.last %}<div class="pagebreak" />{% endif %}
          {% endif %}
        {% endfor %}
        {% for bucket in app.buckets.barcharts %}
          {% if bucket %}
            <h3>{{ bucket.question }}</h3>
            <p>{{ bucket.desc }}</p>
            {% pdf_chart bucket.pk %}
            <section>
              <!-- Table -->
              <table>
                <thead>
                  <tr>
                    <th scope="col">{{ bucket.xlabel }}</th>
                    <th scope="col">{{ bucket.ylabel }}</th>
                  </tr>
                </thead>
                <tbody>
                  {% for bucket_value in bucket.values.all %}
                    <tr>
                      <td>{{ bucket_value.category }}</td>
                      <td>{{ bucket_value.xvalue|nice_float }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
              <!-- End Table Section -->
            </section>
            {% if not forloop.last %}<div class="pagebreak" />{% endif %}
          {% endif %}
        {% endfor %}
        {% for bucket in app.buckets.hbarcharts %}
          {% if bucket %}
            <h3>{{ bucket.question }}</h3>
            <p>{{ bucket.desc }}</p>
            {% pdf_chart bucket.pk %}
            <section>
              <!-- Table -->
              <table>
                <thead>
                  <tr>
                    <th scope="col">{{ bucket.xlabel }}</th>
                    <th scope="col">{{ bucket.ylabel }}</th>
                  </tr>
                </thead>
                <tbody>
                  {% for bucket_value in bucket.values.all %}
                    <tr>
                      <td>{{ bucket_value.category }}</td>
                      <td>{{ bucket_value.xvalue|nice_float }}</td>
                    </tr>
                  {% endfor %}
                </tbody>
              </table>
              <!-- End Table Section -->
            </section>
            {% if not forloop.last %}<div class="pagebreak" />{% endif %}
          {% endif %}
        {% endfor %}
        {% if forloop.last %}<div class="pagebreak" />{% endif %}
      </article>
    {% endfor %}
  </body>
</html>